version: '3.9'

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      APP_HOST: "localhost"
      APP_PORT: "4001"
      APP_DEBUG: "true"
      APP_READ_TIMEOUT: "10"
      APP_ALLOWED_ORIGINS: "*"
      DB_HOST: "postgres"
      DB_NAME: "postgres"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "password"
      DB_PORT: "5432"
      DB_SSLMODE: "disable"
    depends_on:
      - postgres
    command: ["go", "run", "./cmd/server/main.go"]

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
